name: Daily Commit

on:
  schedule:
    - cron: '15 4 * * *'  # Runs at 04:15 UTC every day
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file - 21f1003358@ds.study.iitm.ac.in
        run: |
          echo "Commit made at $(date -u)" >> daily_log.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "21f1003358@ds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Daily commit - $(date -u)" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
